package main

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/nao1215/atago/internal/cli"
)

// tapes are the VHS scripts that render the GIFs the README and the website
// show. Each is the first thing a reader sees about the command it documents.
var tapes = []string{
	"doc/vhs/demo.tape",
	"doc/vhs/review.tape",
	"doc/vhs/snapshot.tape",
}

// tapeCommand is one atago invocation a tape types, together with the directory
// the tape is standing in when it types it. The tapes cd into doc/demo in a
// hidden step, so the bare `passing.atago.yaml` on a later line is a path
// relative to that directory rather than to the repository root.
type tapeCommand struct {
	tape string
	dir  string
	args []string
}

// TestDemoTapes_CommandsStillExist runs every atago command the tapes type and
// requires each to get past dispatch and flag parsing.
//
// A GIF cannot be regenerated byte for byte — VHS output varies with timing,
// fonts and the encoder — so CI cannot diff one to prove a demo is current.
// What can be checked is the thing that actually rots: the command lines inside
// the tape. Rename a subcommand or drop a flag and the next `make demo` quietly
// records a terminal full of usage errors, with the GIF in the README showing
// atago failing to run itself.
//
// The assertion is deliberately not "exits 0": two of these lines exist to show
// a failing run, which is the whole point of the demo. What a rotted tape
// produces instead is a configuration error — an unknown command or an
// unrecognized flag — and that is what fails here.
func TestDemoTapes_CommandsStillExist(t *testing.T) {
	t.Parallel()

	commands := atagoCommandsInTapes(t)
	if len(commands) == 0 {
		t.Fatal("the tapes type no atago commands; the tapes or this parser are wrong")
	}

	for _, cmd := range commands {
		t.Run(cmd.tape+": "+strings.Join(cmd.args, " "), func(t *testing.T) {
			t.Parallel()

			args := rewriteForTest(t, cmd)
			var stdout, stderr bytes.Buffer
			code := cli.Main(args, &stdout, &stderr)
			// ExitConfig is a rotted command line — an unknown subcommand or an
			// unrecognized flag. ExitParse is a spec the demo names that no
			// longer loads. Execution outcomes are deliberately tolerated:
			// ExitFailures is what two of these lines exist to show, and
			// ExitExec is how a demo spec calling echo or printf reports itself
			// on a Windows runner, which is about that runner rather than about
			// the tape.
			if code == cli.ExitConfig || code == cli.ExitParse {
				t.Errorf("`atago %s` no longer runs as the tape types it (exit %d)\nstderr: %s",
					strings.Join(cmd.args, " "), code, stderr.String())
			}
		})
	}
}

// TestDemoTapes_RenderWhereTheDocsLookForThem pins each tape's Output path
// against the pages that embed it. A tape that renders somewhere else leaves the
// README and the website showing a stale image with nothing failing.
func TestDemoTapes_RenderWhereTheDocsLookForThem(t *testing.T) {
	t.Parallel()

	readme := readDoc(t, "README.md")
	for _, tape := range tapes {
		out := tapeOutput(t, tape)
		if out == "" {
			t.Errorf("%s has no Output directive", tape)
			continue
		}
		if _, err := os.Stat(out); err != nil {
			t.Errorf("%s renders %s, which does not exist: %v", tape, out, err)
		}
		if !strings.Contains(readme, out) {
			t.Errorf("%s renders %s, which README.md does not embed", tape, out)
		}
	}
}

// rewriteForTest turns a typed command line into arguments this test can run.
//
// Two rewrites happen. Paths are made absolute against the directory the tape
// is standing in, and the spec files are read from a throwaway copy, so a
// `snapshot update` run here cannot write into the checkout. And the demo's
// opening line runs atago's own E2E suite — seven hundred scenarios that
// `make e2e` already runs, against a binary that has to be on PATH — so its
// directory target is replaced with a single spec. What this test needs from
// that line is that `run --parallel 8 <target>` is still a command; what the
// suite does is not this test's subject.
func rewriteForTest(t *testing.T, cmd tapeCommand) []string {
	t.Helper()

	demo := copyDemoDir(t)
	args := slices.Clone(cmd.args)
	for i, arg := range args {
		switch {
		case strings.HasSuffix(arg, ".atago.yaml"):
			// The tape types a bare filename because it has cd'd into the
			// directory holding it. If that file has been renamed or moved, the
			// demo records a "no such file" instead of a run.
			if _, err := os.Stat(filepath.Join(cmd.dir, arg)); err != nil {
				t.Errorf("%s types %q from %s, which is not there: %v", cmd.tape, arg, cmd.dir, err)
			}
			args[i] = filepath.Join(demo, filepath.Base(arg))
		case arg == suiteTarget:
			args[i] = filepath.Join(demo, "passing.atago.yaml")
		}
	}
	return args
}

// suiteTarget is the directory the demo's opening line runs: atago's own E2E
// suite, which make e2e already runs against a built binary.
const suiteTarget = "./test/e2e/atago"

// copyDemoDir copies doc/demo into a temp directory, snapshots included, so a
// scenario that writes files writes them there.
func copyDemoDir(t *testing.T) string {
	t.Helper()

	dst := t.TempDir()
	root := "doc/demo"
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o750)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o600)
	})
	if err != nil {
		t.Fatalf("copy doc/demo: %v", err)
	}
	return dst
}

// atagoCommandsInTapes returns every atago invocation the tapes type. VHS keeps
// the typed text in `Type "..."` directives; the rest of a tape (Set, Sleep,
// Hide, the shell one-liners that prepare the prompt) is not an invocation. A
// `cd` inside one of those one-liners does decide where the next command runs,
// so it is tracked.
func atagoCommandsInTapes(t *testing.T) []tapeCommand {
	t.Helper()

	var commands []tapeCommand
	for _, tape := range tapes {
		dir := "."
		for _, typed := range typedLines(t, tape) {
			if cd := cdTarget(typed); cd != "" {
				dir = cd
			}
			if !strings.HasPrefix(typed, "atago ") {
				continue
			}
			// The tapes pipe two commands into `head` to keep the frame short;
			// the atago half is what this test runs.
			line, _, _ := strings.Cut(typed, "|")
			commands = append(commands, tapeCommand{
				tape: tape,
				dir:  dir,
				args: strings.Fields(strings.TrimSpace(line))[1:],
			})
		}
	}
	return commands
}

// typedLines returns the text of each `Type "..."` directive in a tape.
func typedLines(t *testing.T, path string) []string {
	t.Helper()

	var typed []string
	for line := range strings.SplitSeq(readDoc(t, path), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, `Type "`) || !strings.HasSuffix(line, `"`) {
			continue
		}
		typed = append(typed, strings.TrimSuffix(strings.TrimPrefix(line, `Type "`), `"`))
	}
	return typed
}

// cdTarget reports the directory a typed shell one-liner changes into, or "".
func cdTarget(typed string) string {
	for part := range strings.SplitSeq(typed, ";") {
		part = strings.TrimSpace(part)
		if after, ok := strings.CutPrefix(part, "cd "); ok {
			return strings.TrimSpace(after)
		}
	}
	return ""
}

// tapeOutput returns the path a tape's Output directive renders to.
func tapeOutput(t *testing.T, path string) string {
	t.Helper()

	for line := range strings.SplitSeq(readDoc(t, path), "\n") {
		if after, ok := strings.CutPrefix(strings.TrimSpace(line), "Output "); ok {
			return strings.TrimSpace(after)
		}
	}
	return ""
}
